version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: malamahanadu_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/fdfs
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: malamahanadu_frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: malamahanadu_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend

  db:
    image: postgres:15
    container_name: malamahanadu_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fdfs
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
